after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash);
  fi
cache:
  directories:
  - $HOME/.m2
  - $HOME/android-sdk-linux
git:
  depth: 10
install: mvn -Ptravis -DskipTests=true -B -V install
language: java
matrix:
  include:
  - env: JACOCO=-Pjacoco
    jdk: openjdk7
  - before_install: if [ ! -d $HOME/android-sdk-linux/platforms ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2
      | bunzip2 | tar xf - -C $HOME; else ls -l $HOME/android-sdk-linux; fi
    env: ANDROID_HOME=$HOME/android-sdk-linux
    jdk: oraclejdk8
  - jdk: oraclejdk9
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn -Ptravis ${JACOCO} test
- find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
- find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
